# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4501c19673561b5d711161f4ddf6d13d"
name = "cart-transform"
application_url = "https://sheffield-iceland-preference-chad.trycloudflare.com"
embedded = true
handle = "cart-transform-60"

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_cart_transforms,write_products"

[auth]
redirect_urls = [
  "https://sheffield-iceland-preference-chad.trycloudflare.com/auth/callback",
  "https://sheffield-iceland-preference-chad.trycloudflare.com/auth/shopify/callback",
  "https://sheffield-iceland-preference-chad.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
