# Learn more about configuring your checkout UI extension:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2025-10"

[[extensions]]
name = "evo Trip Disclosure"
handle = "evo-trip-disclosure"
type = "ui_extension"
uid = "6fed536c-56b8-bfca-098a-cc7264ec61974aac2a2f"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/extension-targets-overview

[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.checkout.delivery-address.render-after"

[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration#api-access
api_access = true
block_progress = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration#network-access
# network_access = true

# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration#metafields

# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_key"
# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_other_key"

# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration#settings-definition

[extensions.settings]
[[extensions.settings.fields]]
key = "text"
type = "single_line_text_field"
name = "Text"

[[extensions.settings.fields]]
key = "link"
type = "single_line_text_field"
name = "Link"
description = "Shopify page URL. Ex. /pages/trip-policies"

[[extensions.settings.fields]]
key = "link_text"
type = "single_line_text_field"
name = "Link text"

[[extensions.settings.fields]]
key = "error_message"
type = "single_line_text_field"
name = "Error message"
description = "Error message shown when user tries to proceed without checking agreement. If no message is set, 'Agreement must be checked to proceed.'"

[[extensions.settings.fields]]
key = "product_type"
type = "single_line_text_field"
name = "Product type"
description = "If a product with this product type is in the cart the agreement checkbox will display"