api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "bundles"
type = "function"
uid = "955d40e3-50c7-8200-880c-a9205be15fb07b9dd8b2"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
